/* AutoGenerated Code, changes may be overwritten
* INPUT GRAMMAR:
* start := wsn '.arm' wsn section=section
* wsn := '[ \t\n]*'
* ws:= '[ \t]+'
* section := text=text | '.data'
* text := wsn '.text' wsn '.global' wsn '_start' wsn '_start:' wsn code=code $
* code := arithmetic
* arithmetic := inst=instruction ws reg1='r[0-9]+' ', ' reg2='r[0-9]+' ', ' reg3='r[0-9]+'
* instruction := 'ADD' | 'ADC' | 'SUB'
*/
type Nullable<T> = T | null;
type $$RuleType<T> = () => Nullable<T>;
interface ASTNodeIntf {
    kind: ASTKinds;
}
export enum ASTKinds {
    start = "start",
    wsn = "wsn",
    ws = "ws",
    section_1 = "section_1",
    section_2 = "section_2",
    text = "text",
    code = "code",
    arithmetic = "arithmetic",
    instruction_1 = "instruction_1",
    instruction_2 = "instruction_2",
    instruction_3 = "instruction_3",
    $EOF = "$EOF",
}
export interface start {
    kind: ASTKinds.start;
    section: section;
}
export type wsn = string;
export type ws = string;
export type section = section_1 | section_2;
export interface section_1 {
    kind: ASTKinds.section_1;
    text: text;
}
export type section_2 = string;
export interface text {
    kind: ASTKinds.text;
    code: code;
}
export type code = arithmetic;
export interface arithmetic {
    kind: ASTKinds.arithmetic;
    inst: instruction;
    reg1: string;
    reg2: string;
    reg3: string;
}
export type instruction = instruction_1 | instruction_2 | instruction_3;
export type instruction_1 = string;
export type instruction_2 = string;
export type instruction_3 = string;
export class Parser {
    private readonly input: string;
    private pos: PosInfo;
    private negating: boolean = false;
    private memoSafe: boolean = true;
    constructor(input: string) {
        this.pos = {overallPos: 0, line: 1, offset: 0};
        this.input = input;
    }
    public reset(pos: PosInfo) {
        this.pos = pos;
    }
    public finished(): boolean {
        return this.pos.overallPos === this.input.length;
    }
    public clearMemos(): void {
    }
    public matchstart($$dpth: number, $$cr?: ErrorTracker): Nullable<start> {
        return this.run<start>($$dpth,
            () => {
                let $scope$section: Nullable<section>;
                let $$res: Nullable<start> = null;
                if (true
                    && this.matchwsn($$dpth + 1, $$cr) !== null
                    && this.regexAccept(String.raw`(?:.arm)`, $$dpth + 1, $$cr) !== null
                    && this.matchwsn($$dpth + 1, $$cr) !== null
                    && ($scope$section = this.matchsection($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.start, section: $scope$section};
                }
                return $$res;
            });
    }
    public matchwsn($$dpth: number, $$cr?: ErrorTracker): Nullable<wsn> {
        return this.regexAccept(String.raw`(?:[ \t\n]*)`, $$dpth + 1, $$cr);
    }
    public matchws($$dpth: number, $$cr?: ErrorTracker): Nullable<ws> {
        return this.regexAccept(String.raw`(?:[ \t]+)`, $$dpth + 1, $$cr);
    }
    public matchsection($$dpth: number, $$cr?: ErrorTracker): Nullable<section> {
        return this.choice<section>([
            () => this.matchsection_1($$dpth + 1, $$cr),
            () => this.matchsection_2($$dpth + 1, $$cr),
        ]);
    }
    public matchsection_1($$dpth: number, $$cr?: ErrorTracker): Nullable<section_1> {
        return this.run<section_1>($$dpth,
            () => {
                let $scope$text: Nullable<text>;
                let $$res: Nullable<section_1> = null;
                if (true
                    && ($scope$text = this.matchtext($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.section_1, text: $scope$text};
                }
                return $$res;
            });
    }
    public matchsection_2($$dpth: number, $$cr?: ErrorTracker): Nullable<section_2> {
        return this.regexAccept(String.raw`(?:.data)`, $$dpth + 1, $$cr);
    }
    public matchtext($$dpth: number, $$cr?: ErrorTracker): Nullable<text> {
        return this.run<text>($$dpth,
            () => {
                let $scope$code: Nullable<code>;
                let $$res: Nullable<text> = null;
                if (true
                    && this.matchwsn($$dpth + 1, $$cr) !== null
                    && this.regexAccept(String.raw`(?:.text)`, $$dpth + 1, $$cr) !== null
                    && this.matchwsn($$dpth + 1, $$cr) !== null
                    && this.regexAccept(String.raw`(?:.global)`, $$dpth + 1, $$cr) !== null
                    && this.matchwsn($$dpth + 1, $$cr) !== null
                    && this.regexAccept(String.raw`(?:_start)`, $$dpth + 1, $$cr) !== null
                    && this.matchwsn($$dpth + 1, $$cr) !== null
                    && this.regexAccept(String.raw`(?:_start:)`, $$dpth + 1, $$cr) !== null
                    && this.matchwsn($$dpth + 1, $$cr) !== null
                    && ($scope$code = this.matchcode($$dpth + 1, $$cr)) !== null
                    && this.match$EOF($$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.text, code: $scope$code};
                }
                return $$res;
            });
    }
    public matchcode($$dpth: number, $$cr?: ErrorTracker): Nullable<code> {
        return this.matcharithmetic($$dpth + 1, $$cr);
    }
    public matcharithmetic($$dpth: number, $$cr?: ErrorTracker): Nullable<arithmetic> {
        return this.run<arithmetic>($$dpth,
            () => {
                let $scope$inst: Nullable<instruction>;
                let $scope$reg1: Nullable<string>;
                let $scope$reg2: Nullable<string>;
                let $scope$reg3: Nullable<string>;
                let $$res: Nullable<arithmetic> = null;
                if (true
                    && ($scope$inst = this.matchinstruction($$dpth + 1, $$cr)) !== null
                    && this.matchws($$dpth + 1, $$cr) !== null
                    && ($scope$reg1 = this.regexAccept(String.raw`(?:r[0-9]+)`, $$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:, )`, $$dpth + 1, $$cr) !== null
                    && ($scope$reg2 = this.regexAccept(String.raw`(?:r[0-9]+)`, $$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:, )`, $$dpth + 1, $$cr) !== null
                    && ($scope$reg3 = this.regexAccept(String.raw`(?:r[0-9]+)`, $$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.arithmetic, inst: $scope$inst, reg1: $scope$reg1, reg2: $scope$reg2, reg3: $scope$reg3};
                }
                return $$res;
            });
    }
    public matchinstruction($$dpth: number, $$cr?: ErrorTracker): Nullable<instruction> {
        return this.choice<instruction>([
            () => this.matchinstruction_1($$dpth + 1, $$cr),
            () => this.matchinstruction_2($$dpth + 1, $$cr),
            () => this.matchinstruction_3($$dpth + 1, $$cr),
        ]);
    }
    public matchinstruction_1($$dpth: number, $$cr?: ErrorTracker): Nullable<instruction_1> {
        return this.regexAccept(String.raw`(?:ADD)`, $$dpth + 1, $$cr);
    }
    public matchinstruction_2($$dpth: number, $$cr?: ErrorTracker): Nullable<instruction_2> {
        return this.regexAccept(String.raw`(?:ADC)`, $$dpth + 1, $$cr);
    }
    public matchinstruction_3($$dpth: number, $$cr?: ErrorTracker): Nullable<instruction_3> {
        return this.regexAccept(String.raw`(?:SUB)`, $$dpth + 1, $$cr);
    }
    public test(): boolean {
        const mrk = this.mark();
        const res = this.matchstart(0);
        const ans = res !== null;
        this.reset(mrk);
        return ans;
    }
    public parse(): ParseResult {
        const mrk = this.mark();
        const res = this.matchstart(0);
        if (res)
            return {ast: res, errs: []};
        this.reset(mrk);
        const rec = new ErrorTracker();
        this.clearMemos();
        this.matchstart(0, rec);
        const err = rec.getErr()
        return {ast: res, errs: err !== null ? [err] : []}
    }
    public mark(): PosInfo {
        return this.pos;
    }
    private loop<T>(func: $$RuleType<T>, star: boolean = false): Nullable<T[]> {
        const mrk = this.mark();
        const res: T[] = [];
        for (;;) {
            const t = func();
            if (t === null) {
                break;
            }
            res.push(t);
        }
        if (star || res.length > 0) {
            return res;
        }
        this.reset(mrk);
        return null;
    }
    private run<T>($$dpth: number, fn: $$RuleType<T>): Nullable<T> {
        const mrk = this.mark();
        const res = fn()
        if (res !== null)
            return res;
        this.reset(mrk);
        return null;
    }
    private choice<T>(fns: Array<$$RuleType<T>>): Nullable<T> {
        for (const f of fns) {
            const res = f();
            if (res !== null) {
                return res;
            }
        }
        return null;
    }
    private regexAccept(match: string, dpth: number, cr?: ErrorTracker): Nullable<string> {
        return this.run<string>(dpth,
            () => {
                const reg = new RegExp(match, "y");
                const mrk = this.mark();
                reg.lastIndex = mrk.overallPos;
                const res = this.tryConsume(reg);
                if(cr) {
                    cr.record(mrk, res, {
                        kind: "RegexMatch",
                        // We substring from 3 to len - 1 to strip off the
                        // non-capture group syntax added as a WebKit workaround
                        literal: match.substring(3, match.length - 1),
                        negated: this.negating,
                    });
                }
                return res;
            });
    }
    private tryConsume(reg: RegExp): Nullable<string> {
        const res = reg.exec(this.input);
        if (res) {
            let lineJmp = 0;
            let lind = -1;
            for (let i = 0; i < res[0].length; ++i) {
                if (res[0][i] === "\n") {
                    ++lineJmp;
                    lind = i;
                }
            }
            this.pos = {
                overallPos: reg.lastIndex,
                line: this.pos.line + lineJmp,
                offset: lind === -1 ? this.pos.offset + res[0].length : (res[0].length - lind - 1)
            };
            return res[0];
        }
        return null;
    }
    private noConsume<T>(fn: $$RuleType<T>): Nullable<T> {
        const mrk = this.mark();
        const res = fn();
        this.reset(mrk);
        return res;
    }
    private negate<T>(fn: $$RuleType<T>): Nullable<boolean> {
        const mrk = this.mark();
        const oneg = this.negating;
        this.negating = !oneg;
        const res = fn();
        this.negating = oneg;
        this.reset(mrk);
        return res === null ? true : null;
    }
    private memoise<K>(rule: $$RuleType<K>, memo: Map<number, [Nullable<K>, PosInfo]>): Nullable<K> {
        const $scope$pos = this.mark();
        const $scope$memoRes = memo.get($scope$pos.overallPos);
        if(this.memoSafe && $scope$memoRes !== undefined) {
        this.reset($scope$memoRes[1]);
        return $scope$memoRes[0];
        }
        const $scope$result = rule();
        if(this.memoSafe)
        memo.set($scope$pos.overallPos, [$scope$result, this.mark()]);
        return $scope$result;
    }
    private match$EOF(et?: ErrorTracker): Nullable<{kind: ASTKinds.$EOF}> {
        const res: {kind: ASTKinds.$EOF} | null = this.finished() ? { kind: ASTKinds.$EOF } : null;
        if(et)
            et.record(this.mark(), res, { kind: "EOF", negated: this.negating });
        return res;
    }
}
export function parse(s: string): ParseResult {
    const p = new Parser(s);
    return p.parse();
}
export interface ParseResult {
    ast: Nullable<start>;
    errs: SyntaxErr[];
}
export interface PosInfo {
    readonly overallPos: number;
    readonly line: number;
    readonly offset: number;
}
export interface RegexMatch {
    readonly kind: "RegexMatch";
    readonly negated: boolean;
    readonly literal: string;
}
export type EOFMatch = { kind: "EOF"; negated: boolean };
export type MatchAttempt = RegexMatch | EOFMatch;
export class SyntaxErr {
    public pos: PosInfo;
    public expmatches: MatchAttempt[];
    constructor(pos: PosInfo, expmatches: MatchAttempt[]) {
        this.pos = pos;
        this.expmatches = [...expmatches];
    }
    public toString(): string {
        return `Syntax Error at line ${this.pos.line}:${this.pos.offset}. Expected one of ${this.expmatches.map(x => x.kind === "EOF" ? " EOF" : ` ${x.negated ? 'not ': ''}'${x.literal}'`)}`;
    }
}
class ErrorTracker {
    private mxpos: PosInfo = {overallPos: -1, line: -1, offset: -1};
    private regexset: Set<string> = new Set();
    private pmatches: MatchAttempt[] = [];
    public record(pos: PosInfo, result: any, att: MatchAttempt) {
        if ((result === null) === att.negated)
            return;
        if (pos.overallPos > this.mxpos.overallPos) {
            this.mxpos = pos;
            this.pmatches = [];
            this.regexset.clear()
        }
        if (this.mxpos.overallPos === pos.overallPos) {
            if(att.kind === "RegexMatch") {
                if(!this.regexset.has(att.literal))
                    this.pmatches.push(att);
                this.regexset.add(att.literal);
            } else {
                this.pmatches.push(att);
            }
        }
    }
    public getErr(): SyntaxErr | null {
        if (this.mxpos.overallPos !== -1)
            return new SyntaxErr(this.mxpos, this.pmatches);
        return null;
    }
}